# Generated by Django 3.2.20 on 2023-08-27 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('libro', models.CharField(choices=[('ficcionLit', 'FiccionLit'), ('ciencias', 'Ciencias'), ('infantilJuv', 'InfantilJuv'), ('comicsManga', 'ComicsManga'), ('autoayuda', 'Autoayuda'), ('academicoIdioma', 'AcademicoIdioma'), ('otro', 'Otro')], default='ficcionLit', max_length=15)),
                ('autor', models.CharField(max_length=60)),
                ('editorial', models.CharField(max_length=60)),
                ('edicion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('telefonoContacto', models.IntegerField()),
                ('emailContacto', models.EmailField(max_length=254)),
                ('imagenLibro', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario', '-fechaPublicacion'],
            },
        ),
    ]
