# Generated by Django 3.2.20 on 2023-08-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='libro',
            new_name='libroCategoria',
        ),
    ]
