# Generated by Django 3.2.20 on 2023-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_libro_libro_librocategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='edicion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='emailContacto',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='imagenLibro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='libroCategoria',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='telefonoContacto',
        ),
    ]
