# Generated by Django 3.2.20 on 2023-08-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20230827_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='edicion',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(default='editorial', max_length=60),
        ),
        migrations.AddField(
            model_name='libro',
            name='emailContacto',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagenLibro',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='libroCategoria',
            field=models.CharField(choices=[('ficcionLit', 'FiccionLit'), ('ciencias', 'Ciencias'), ('infantilJuv', 'InfantilJuv'), ('otro', 'Otro')], default='ficcionLit', max_length=15),
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='telefonoContacto',
            field=models.IntegerField(default=1537053713),
            preserve_default=False,
        ),
    ]
