# Generated by Django 3.2.20 on 2023-08-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_auto_20230827_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='libro',
            name='emailContacto',
            field=models.EmailField(max_length=254),
        ),
    ]
