# Generated by Django 3.2.20 on 2023-08-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_auto_20230827_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='libroCategoria',
            field=models.CharField(choices=[('ficcion', 'FiccionLit'), ('ciencias', 'Ciencias'), ('infantil', 'Infantil'), ('otro', 'Otro')], default='ficcion', max_length=15),
        ),
    ]
