# Generated by Django 3.2.20 on 2023-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagenLibro',
            field=models.ImageField(blank=True, null=True, upload_to='AppCoder/imagenes/'),
        ),
    ]
